# permissions for end users to edit servicewatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicewatcher-editor-role
rules:
- apiGroups:
  - batch.operator.jubril.me
  resources:
  - servicewatchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.operator.jubril.me
  resources:
  - servicewatchers/status
  verbs:
  - get
